<a href="https://colab.research.google.com/github/Bee-Chang/Machine-Learning-Projects/blob/main/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Naive Bayes **

The kids can play outside if the weather and temp permit. Any adversarial weather or high or low temp, the kids can't.

In [ ]:
import pandas as pd
import numpy as np

df=pd.read_csv("play_or_not.csv")
df

In [ ]:
#In order to process we must turn those categorical values into numberic values
#Import LabelEncoder
from sklearn import preprocessing

#creating labelEncoder
le = preprocessing.LabelEncoder()

#Using .fit_transform function to fit label
#encoder and return encoded label
weather_label=le.fit_transform(df['Weather'])

#printing weather_label
weather_label

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [ ]:
#repeat it for temp label
temp_label=le.fit_transform(df['Temp'])

#printing temp_label
temp_label

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [ ]:
#repeat it for play label
play_label=le.fit_transform(df['Play'])

#printing play_label
play_label

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [ ]:
#we'll use zip method in this function called merge to combine the two labels: weather and temp
def merge (list1, list2):
  merged_list=tuple(zip(list1, list2))
  return merged_list

features=merge(weather_label, temp_label)
features


((2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2))

In [ ]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(features,play_label)

#Predict Output
predicted= model.predict([[0,2]]) # 0:Overcast, 2:Mild
print ("Predicted Value:", predicted)

Predicted Value: [1]


### From the above result, 1 indicates that the players can 'play'.

# **Naive Bayes using Multiple Labels**

In [ ]:
#import scikit-learn dataset library
from sklearn import datasets

#load dataset
wine=datasets.load_wine()


In [ ]:
df=pd.read_csv("wine.csv")
df.head()


14.23  1.71  2.43  15.6  127   2.8  ...  2.29  5.64  1.04  3.92  1065  1
0  13.20  1.78  2.14  11.2  100  2.65  ...  1.28  4.38  1.05  3.40  1050  1
1  13.16  2.36  2.67  18.6  101  2.80  ...  2.81  5.68  1.03  3.17  1185  1
2  14.37  1.95  2.50  16.8  113  3.85  ...  2.18  7.80  0.86  3.45  1480  1
3  13.24  2.59  2.87  21.0  118  2.80  ...  1.82  4.32  1.04  2.93   735  1
4  14.20  1.76  2.45  15.2  112  3.27  ...  1.97  6.75  1.05  2.85  1450  1

[5 rows x 14 columns]

In [ ]:
df.columns= ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline','class']
df.head()

alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  class
0    13.20        1.78  2.14  ...                          3.40     1050      1
1    13.16        2.36  2.67  ...                          3.17     1185      1
2    14.37        1.95  2.50  ...                          3.45     1480      1
3    13.24        2.59  2.87  ...                          2.93      735      1
4    14.20        1.76  2.45  ...                          2.85     1450      1

[5 rows x 14 columns]

In [ ]:
x_data = df[['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']]
y_data = df['class']

In [ ]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3,random_state=109) # 70% training and 30% test

In [ ]:
#This is model generation

#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

#Train the model using the training sets
model.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)

#This is to evaluate the model
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


Accuracy: 0.9814814814814815
